version: '3.7'

services:
  postgres:
    image: postgres:13.3-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bet_api:
    image: bet_api:latest
    build: .
    restart: always
    container_name: bet_api
    ports:
      - "8080:8080"
    volumes:
      - ./boot.prod.yaml:/app/boot.yaml