version: '3.7'

services:
  postgres:
    image: postgres:13.3-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  go_app:
    image: rk_echo:latest
    build: .
    restart: always
    container_name: go_app
    ports:
      - "8080:8080"
    volumes:
      - ./boot.prod.yaml:/app/boot.yaml