definitions:
  errutil.EchoErrorStruct:
    properties:
      code:
        type: integer
      error:
        type: string
      info: {}
    type: object
  models.Transaction:
    properties:
      bought_at:
        type: string
      buying_price:
        type: number
      id:
        type: integer
      wager_id:
        type: integer
    type: object
  models.Wager:
    properties:
      amount_sold:
        type: number
      current_selling_price:
        type: number
      id:
        type: integer
      odds:
        type: number
      percentage_sold:
        type: number
      placed_at:
        type: string
      selling_percentage:
        type: number
      selling_price:
        type: number
      total_wager_value:
        type: number
    type: object
  wagerdto.BuyWagerInput:
    properties:
      buying_price:
        type: number
    required:
    - buying_price
    type: object
  wagerdto.PlaceWagerInput:
    properties:
      odds:
        type: number
      selling_percentage:
        maximum: 100
        minimum: 1
        type: number
      selling_price:
        type: number
      total_wager_value:
        type: number
    required:
    - odds
    - selling_percentage
    - selling_price
    - total_wager_value
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample rk-demo echo server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Demo Echo API Framework
  version: "1.0"
paths:
  /buy/{wager_id}:
    post:
      parameters:
      - description: ID of the wager to buy
        in: path
        name: wager_id
        required: true
        type: string
      - description: Input Required
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/wagerdto.BuyWagerInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Transaction'
        default:
          description: ""
          schema:
            $ref: '#/definitions/errutil.EchoErrorStruct'
      summary: Buy a wager
      tags:
      - Wager
  /wagers:
    get:
      parameters:
      - description: Page
        in: query
        name: page
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      - description: Sort
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Transaction'
        default:
          description: ""
          schema:
            $ref: '#/definitions/errutil.EchoErrorStruct'
      summary: List all wager
      tags:
      - Wager
    post:
      parameters:
      - description: Input Required
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/wagerdto.PlaceWagerInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Wager'
        default:
          description: ""
          schema:
            $ref: '#/definitions/errutil.EchoErrorStruct'
      summary: Place a wager
      tags:
      - Wager
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
